### ISSUE TITLE
Should new ENUM value on consumer break contract?

### ISSUE THREAD

**Issue by montete** [HLTech/judge-d#151]
Hi.

We have recently bumped into problem while validating contract ENUM field.

Since we did not want to have provider sent consumer ENUM values that it would not be able to process, we added new values to consumer first. 

That made our validation fail the contract: 
`Schema with id null has not matching enums - consumer: [A, B, C, D, E], provider: [A, B, C]`

I understand that general approach is that consumer should be a subset of provider. 
This approach in ENUM fields, can potentially break contract by sending consumer values that he cannot process.
Example:
provider: [A, B, C]
consumer: [A, B]

Contract is valid, when message with enum value of C is being sent to consumer.
Consumer however, cannot process it, and breaks on valid contract.

Shouldn't this, in this particular example, be other way around?

**Comment by Felipe444** [comment]
Yes, a provider should offer a superset of what a consumer expects. By definition the provider can offer more. If the consumer is not willing to use what the provider offers, it should ignore that. The consumer should be ready for that. If you would like to extend an enum in a JMS contract on topic destination, firstly you need to extend provider so that it offers more, subsequently you should adjust consumer's expectations.
